"""
Roadmap fase 15.5 — the multimodal node family: audio.transcribe, image.ocr,
image.generate and tts.

The providers themselves are stubbed: what these tests pin down is the part
this codebase owns — workspace path confinement, the "path defaults to the node
input" contract shared with doc.convert, the shape of each node's output, and
the fact that generated bytes land on disk instead of in the run log.
"""

import asyncio
import base64

import pytest

from app.core.config import settings
from app.services import image_service, speech_service
from app.workflow.nodes import multimodal
from app.workflow.registry import NODE_HANDLERS

_PNG = base64.b64decode(
    b"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="
)


@pytest.fixture()
def workspace(monkeypatch, tmp_path):
    monkeypatch.setattr(settings, "graph_workflow_files_dir", str(tmp_path))
    return tmp_path


# ── registration ─────────────────────────────────────────────────────────────

@pytest.mark.parametrize("ntype", ["audio.transcribe", "image.ocr", "image.generate", "tts"])
def test_node_is_registered(ntype):
    assert ntype in NODE_HANDLERS


@pytest.mark.parametrize("ntype", ["audio.transcribe", "image.ocr", "image.generate", "tts"])
def test_node_is_in_the_catalog(ntype):
    from app.data.node_catalog import _STATIC_NODES

    entry = next((n for n in _STATIC_NODES if n.type == ntype), None)
    assert entry is not None, f"{ntype} missing from the palette catalog"
    assert entry.params_schema, "a node with no params cannot be configured in the editor"


# ── audio.transcribe ─────────────────────────────────────────────────────────

def test_audio_transcribe_returns_text_and_segments(workspace, monkeypatch):
    (workspace / "clip.mp3").write_bytes(b"not really audio")
    seen = {}

    async def fake_transcribe(path, *, model=None, language=None):
        seen.update(path=path, model=model, language=language)
        # speech_service.transcribe already strips the text, so the node is a
        # pass-through here: what it adds is the workspace-relative path.
        return {"text": "hello world", "segments": [{"start": 0, "text": "hello world"}],
                "language": "en", "model": "whisper-1", "duration": 1.5}

    monkeypatch.setattr(speech_service, "transcribe", fake_transcribe)
    out = asyncio.run(multimodal._exec_audio_transcribe({"path": "clip.mp3", "language": "en"}, None))

    assert out["text"] == "hello world"
    assert out["segments"][0]["text"] == "hello world"
    assert out["duration"] == 1.5 and out["model"] == "whisper-1"
    # The node reports the path the user typed, not the absolute one it resolved.
    assert out["path"] == "clip.mp3"
    assert seen["language"] == "en"
    assert seen["path"].endswith("clip.mp3") and seen["path"] != "clip.mp3"


def test_audio_transcribe_defaults_the_path_to_the_node_input(workspace, monkeypatch):
    """Same contract as doc.convert: a file.watch trigger can feed it directly."""
    (workspace / "from-input.wav").write_bytes(b"x")

    async def fake_transcribe(path, **kwargs):
        return {"text": "ok", "segments": [], "language": None, "model": "m", "duration": None}

    monkeypatch.setattr(speech_service, "transcribe", fake_transcribe)
    out = asyncio.run(multimodal._exec_audio_transcribe({}, "from-input.wav"))
    assert out["path"] == "from-input.wav"


def test_audio_transcribe_missing_file(workspace):
    with pytest.raises(FileNotFoundError, match="audio.transcribe"):
        asyncio.run(multimodal._exec_audio_transcribe({"path": "nope.mp3"}, None))


def test_audio_transcribe_cannot_escape_the_workspace(workspace):
    with pytest.raises(ValueError, match="escapes the workspace"):
        asyncio.run(multimodal._exec_audio_transcribe({"path": "../../etc/passwd"}, None))


def test_audio_transcribe_requires_a_path(workspace):
    with pytest.raises(ValueError, match="'path' is required"):
        asyncio.run(multimodal._exec_audio_transcribe({}, None))


# ── image.ocr ────────────────────────────────────────────────────────────────

def test_image_ocr_sends_the_image_as_a_data_uri(workspace, monkeypatch):
    (workspace / "shot.png").write_bytes(_PNG)
    captured = {}

    async def fake_complete(request):
        captured["request"] = request
        return {"choices": [{"message": {"content": "INVOICE 42\n"}}], "usage": {}}, "miss"

    monkeypatch.setattr("app.workflow.nodes.llm._cached_complete", fake_complete)
    out = asyncio.run(multimodal._exec_image_ocr(None, "default", {"path": "shot.png"}, None))

    assert out["text"] == "INVOICE 42"
    assert out["chars"] == len("INVOICE 42")
    parts = captured["request"].messages[0].content
    assert isinstance(parts, list), "the vision call must send multimodal content parts"
    assert parts[1]["image_url"]["url"].startswith("data:image/png;base64,")


def test_image_ocr_prompt_can_be_overridden(workspace, monkeypatch):
    (workspace / "shot.png").write_bytes(_PNG)
    captured = {}

    async def fake_complete(request):
        captured["request"] = request
        return {"choices": [{"message": {"content": "x"}}], "usage": {}}, "miss"

    monkeypatch.setattr("app.workflow.nodes.llm._cached_complete", fake_complete)
    asyncio.run(multimodal._exec_image_ocr(
        None, "default", {"path": "shot.png", "prompt": "Only the total"}, None))
    assert captured["request"].messages[0].content[0]["text"] == "Only the total"


def test_image_ocr_missing_file(workspace):
    with pytest.raises(FileNotFoundError, match="image.ocr"):
        asyncio.run(multimodal._exec_image_ocr(None, "default", {"path": "gone.png"}, None))


# ── image.generate ───────────────────────────────────────────────────────────

def test_image_generate_writes_the_file_and_reports_the_path(workspace, monkeypatch):
    async def fake_generate(prompt, width=1024, height=1024, provider=None):
        return {"b64_json": base64.b64encode(_PNG).decode(), "provider": "gemini", "model": "m"}

    monkeypatch.setattr(image_service, "generate_image", fake_generate)
    out = asyncio.run(multimodal._exec_image_generate({"prompt": "a cat"}, None))

    assert out["path"].startswith("generated/") and out["path"].endswith(".png")
    assert out["bytes"] == len(_PNG)
    assert out["provider"] == "gemini"
    # The bytes go to disk, not into the output: the run log must stay readable.
    assert "b64_json" not in out
    assert (workspace / out["path"]).read_bytes() == _PNG


def test_image_generate_honours_an_explicit_path(workspace, monkeypatch):
    async def fake_generate(prompt, **kwargs):
        return {"b64_json": base64.b64encode(_PNG).decode(), "provider": "p", "model": "m"}

    monkeypatch.setattr(image_service, "generate_image", fake_generate)
    out = asyncio.run(multimodal._exec_image_generate(
        {"prompt": "x", "path": "art/cat.png"}, None))
    assert out["path"] == "art/cat.png"
    assert (workspace / "art" / "cat.png").is_file(), "nested output dirs must be created"


def test_image_generate_takes_the_prompt_from_the_input(workspace, monkeypatch):
    seen = {}

    async def fake_generate(prompt, **kwargs):
        seen["prompt"] = prompt
        return {"b64_json": base64.b64encode(_PNG).decode(), "provider": "p", "model": "m"}

    monkeypatch.setattr(image_service, "generate_image", fake_generate)
    asyncio.run(multimodal._exec_image_generate({}, "a dog on a bike"))
    assert seen["prompt"] == "a dog on a bike"


def test_image_generate_requires_a_prompt(workspace):
    with pytest.raises(ValueError, match="'prompt' is required"):
        asyncio.run(multimodal._exec_image_generate({}, None))


def test_image_generate_cannot_write_outside_the_workspace(workspace, monkeypatch):
    async def fake_generate(prompt, **kwargs):
        return {"b64_json": base64.b64encode(_PNG).decode(), "provider": "p", "model": "m"}

    monkeypatch.setattr(image_service, "generate_image", fake_generate)
    with pytest.raises(ValueError, match="escapes the workspace"):
        asyncio.run(multimodal._exec_image_generate({"prompt": "x", "path": "../evil.png"}, None))


# ── tts ──────────────────────────────────────────────────────────────────────

def test_tts_writes_audio_and_reports_metadata(workspace, monkeypatch):
    async def fake_synth(text, *, model=None, voice=None, response_format="mp3"):
        return b"ID3-audio-bytes"

    monkeypatch.setattr(speech_service, "synthesize", fake_synth)
    out = asyncio.run(multimodal._exec_tts({"text": "ciao", "voice": "nova"}, None))

    assert out["path"].endswith(".mp3")
    assert out["bytes"] == len(b"ID3-audio-bytes")
    assert out["voice"] == "nova"
    assert out["chars"] == 4
    assert (workspace / out["path"]).read_bytes() == b"ID3-audio-bytes"


def test_tts_format_drives_the_extension(workspace, monkeypatch):
    async def fake_synth(text, *, model=None, voice=None, response_format="mp3"):
        assert response_format == "wav"
        return b"RIFF"

    monkeypatch.setattr(speech_service, "synthesize", fake_synth)
    out = asyncio.run(multimodal._exec_tts({"text": "hi", "format": "wav"}, None))
    assert out["path"].endswith(".wav") and out["format"] == "wav"


def test_tts_rejects_an_unknown_format(workspace):
    with pytest.raises(ValueError, match="unsupported format"):
        asyncio.run(multimodal._exec_tts({"text": "hi", "format": "exe"}, None))


def test_tts_requires_text(workspace):
    with pytest.raises(ValueError, match="'text' is required"):
        asyncio.run(multimodal._exec_tts({}, None))


def test_tts_surfaces_a_provider_error_as_a_node_failure(workspace, monkeypatch):
    async def boom(text, **kwargs):
        raise speech_service.SpeechError("no TTS model configured")

    monkeypatch.setattr(speech_service, "synthesize", boom)
    with pytest.raises(RuntimeError, match="no TTS model configured"):
        asyncio.run(multimodal._exec_tts({"text": "hi"}, None))
